### ISSUE TITLE
Invalid typing for  `df.to_csv`

### ISSUE THREAD

**Issue by JensHeinrich** [pandas-dev/pandas-stubs#962]
There probably should be a switch like

```
if sys.version_info >= (3, 12):
    CSVQuoting: TypeAlias = Literal[0, 1, 2, 3, 4,5]
else:
    CSVQuoting: TypeAlias = Literal[0, 1, 2, 3]
```
at
https://github.com/pandas-dev/pandas-stubs/blob/48ca4b0d70f0695da6d452f7e203f05ad983913a/pandas-stubs/_typing.pyi#L741

as [QUOTE_STRINGS](https://docs.python.org/3/library/csv.html#csv.QUOTE_STRINGS) and [QUOTE_NOTNULL](https://docs.python.org/3/library/csv.html#csv.QUOTE_NOTNULL) options have been added in python 3.12
